version: '3.7'

services:
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME:-cinephoriaproject}
      MYSQL_USER: ${DATABASE_USER:-cinephoria}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-cinephoriapassword}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-cinephoriapassword}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-cinephoriapassword}

volumes:
  db_data:
  mongodb_data:
