name: Deploy Symfony to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Docker and Docker Compose on VPS
        run: |
          ssh -o StrictHostKeyChecking=no debian@5.196.21.36 "sudo apt-get update && sudo apt-get install -y docker.io docker-compose git"

      - name: Remove existing directory and clone repository
        run: |
          ssh -o StrictHostKeyChecking=no debian@5.196.21.36 "sudo rm -rf /var/www/cinephoria && sudo git clone https://github.com/kyllian-claveau/CinephoriaV2.git /var/www/cinephoria"

      - name: Create .env file on the VPS with secrets
        run: |
          ssh debian@5.196.21.36 "echo 'APP_ENV=prod' | sudo tee /var/www/cinephoria/.env > /dev/null && \
                                  echo 'APP_SECRET=${{ secrets.APP_SECRET }}' | sudo tee -a /var/www/cinephoria/.env > /dev/null && \
                                  echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' | sudo tee -a /var/www/cinephoria/.env > /dev/null && \
                                  echo 'MESSENGER_TRANSPORT_DSN=${{ secrets.MESSENGER_TRANSPORT_DSN }}' | sudo tee -a /var/www/cinephoria/.env > /dev/null && \
                                  echo 'MAILER_DSN=${{ secrets.MAILER_DSN }}' | sudo tee -a /var/www/cinephoria/.env > /dev/null && \
                                  echo 'CORS_ALLOW_ORIGIN=${{ secrets.CORS_ALLOW_ORIGIN }}' | sudo tee -a /var/www/cinephoria/.env > /dev/null && \
                                  echo 'JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}' | sudo tee -a /var/www/cinephoria/.env > /dev/null && \
                                  echo 'JWT_PUBLIC_KEY=${{ secrets.JWT_PUBLIC_KEY }}' | sudo tee -a /var/www/cinephoria/.env > /dev/null && \
                                  echo 'JWT_PASSPHRASE=${{ secrets.JWT_PASSPHRASE }}' | sudo tee -a /var/www/cinephoria/.env > /dev/null && \
                                  echo 'MONGODB_DSN=${{ secrets.MONGODB_DSN }}' | sudo tee -a /var/www/cinephoria/.env > /dev/null && \
                                  echo 'MONGODB_DB=${{ secrets.MONGODB_DB }}' | sudo tee -a /var/www/cinephoria/.env > /dev/null && \
                                  echo 'MONGODB_COLLECTION=${{ secrets.MONGODB_COLLECTION }}' | sudo tee -a /var/www/cinephoria/.env > /dev/null"

      - name: Deploy with Docker Compose
        run: |
          ssh debian@5.196.21.36 "cd /var/www/cinephoria && sudo docker-compose pull && sudo docker-compose up -d --force-recreate"
